name:                honeypot
version:             0.1.0.0
github:              "patriques82/honeypot"
license:             BSD3
author:              "Patrik Nygren"
maintainer:          "patriknygren82@gmail.com"
copyright:           "2019 Patrik Nygren"

extra-source-files:
- README.md
- ChangeLog.md

# synopsis:            Honeypot challange clone
# category:            AI

description:         Please see the README on GitHub at <https://github.com/patriques82/honeypot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - mtl
  - matrix
  - free
  - lens-simple

executables:
  honeypot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honeypot
    - gloss

tests:
  honeypot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honeypot
    - tasty
    - tasty-quickcheck
    - tasty-hunit
